// SPDX-FileCopyrightText: 2026 Leon Manuel Töpper
// SPDX-License-Identifier: AGPL-3.0-only

// AUTO-GENERATED — do not edit manually
// Generated by scripts/build_macos.sh
class BuildInfo {
  static const String version = '0.5.2';
  static const String versionName = '0.5.2 Closed Beta';
  static const int buildNumber = 38;
  static const String fullVersion = '0.5.2 Build 38';
}
