// SPDX-FileCopyrightText: 2026 Leon Manuel Töpper
// SPDX-License-Identifier: AGPL-3.0-only

// AUTO-GENERATED — do not edit manually
// Generated by scripts/build_macos.sh
class BuildInfo {
  static const String version = '0.5.1';
  static const String versionName = '0.5.1 Closed Beta';
  static const int buildNumber = 36;
  static const String fullVersion = '0.5.1 Build 36';
}
